version: '3'

services:
  web: 
    build:
      context: .
      dockerfile: docker/dev/python/Dockerfile
    environment:
      PYTHONUNBUFFERED: 1
    env_file:
      - .env
    volumes:
      - ./app:/app
    ports:
      - 80:8000
    restart: always
    command: python manage.py runserver 0.0.0.0:8000
    